### ISSUE TITLE
Redwood's port 8460 not open after install_bootstrap?

### ISSUE THREAD

**Issue by brainstorm** [BD2KGenomics/dcc-ops#108]
The `test/integration.sh` script passes successfully:

```
ubuntu@ip-172-31-21-238:~/dcc-ops/test$ ./integration.sh
[2017-07-31 10:32:21.395][INFO  ][main:16 ] deleted old outputs
[2017-07-31 10:32:21.624][INFO  ][main:19 ] generated testing access token: 6d186440-be4d-48aa-ab75-7c2e52aa2a2c
[2017-07-31 10:32:21.628][INFO  ][main:22 ] got redwood endpoint from dcc-ops/redwood/.env: dcc.umccr.nopcode.org
[2017-07-31 10:32:21.631][INFO  ][main:24 ] doing upload with /home/ubuntu/dcc-ops/test/manifest.tsv
2017-07-31 10:32:22,143 INFO main:884 validated all metadata objects for output
2017-07-31 10:32:22,144 INFO main:890 number of metadata files written: 2
2017-07-31 10:32:22,144 INFO main:899 Uploading files.
2017-07-31 10:32:22,144 INFO main:900 NOTE: If it hangs IP may be blocked
2017-07-31 10:32:22,144 INFO main:950 counts	{"bundlesFound": 1}
2017-07-31 10:32:22,145 INFO main:950 counts	{"bundlesFound": 2}
2017-07-31 10:32:22,145 INFO register_upload:536 registering upload redwood metadata: dcc-metadata-client -m /outputs/registration.tsv -o /outputs/redwoodUploadManifest
2017-07-31 10:32:26,811 INFO perform_upload:552 performing upload: icgc-storage-client upload --manifest /outputs/redwoodUploadManifest/ca3ccf42-c0ea-553b-b19f-e34570a1f03c --force
2017-07-31 10:32:34,348 INFO main:966 now generate upload receipt
2017-07-31 10:32:34,350 INFO main:997 Upload succeeded. A detailed log is at: /outputs/spinnaker.log
2017-07-31 10:32:34,350 INFO main:999 Upload took 12.223798 s.
[2017-07-31 10:32:34.612][INFO  ][main:31 ] the uploaded bundle with id 5c58e075-a2ba-536c-b039-f0418746dcea has metadata.json with object id da379c6c-f446-539a-a6f5-5b1e087febc9
[2017-07-31 10:32:34.614][INFO  ][main:33 ] downloading metadata.json with object id da379c6c-f446-539a-a6f5-5b1e087febc9
Downloading...
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[1/1] Downloading object: da379c6c-f446-539a-a6f5-5b1e087febc9 (metadata.json)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
100% [##################################################]  Parts: 1/1, Checksum: 100%, Write/sec: 0B/s, Read/sec: 13.7K/s
Finalizing...
Total execution time:        126.3 ms
Total bytes read    :           1,587
Total bytes written :               0
Verifying checksum...Done.
[2017-07-31 10:32:38.954][INFO  ][main:44 ] TEST SUCCESS
```

But when following the [spinnaker client](https://github.com/BD2KGenomics/dcc-spinnaker-client) README ([and after correctly mapping the `samples` docker volume](https://github.com/BD2KGenomics/dcc-spinnaker-client/issues/37)), the spinnaker client times out since it cannot connect to the storage domain/endpoint:

```
ubuntu@ip-172-31-21-238:~/spinnaker-test$ docker run -it -e REDWOOD_ENDPOINT=https://storage.dcc.umccr.nopcode.org -v $(pwd)/application-redwood.properties:/dcc/dcc-redwood-client/conf/application-redwood.properties -v $(pwd):/data -v $(pwd)/three_manifest.tsv:/manifests/manifest.tsv -v $(pwd)/outputs:/outputs -v $(pwd)/samples:/samples quay.io/ucsc_cgl/core-client:1.1.1 spinnaker-upload /manifests/manifest.tsv
2017-07-31 10:20:56,808 INFO sha1sum:34 Calculating the sha1 sum for normal.fastq.gz.
100%|##############################################################################################################################################################################################################################################| 42.0/42.0 [00:00<00:00, 1.02MB/s]
2017-07-31 10:20:56,809 INFO sha1sum:42 sha1 sum done for normal.fastq.gz
2017-07-31 10:20:56,809 INFO sha1sum:34 Calculating the sha1 sum for tumor.fastq.gz.
100%|##############################################################################################################################################################################################################################################| 42.0/42.0 [00:00<00:00, 1.05MB/s]
2017-07-31 10:20:56,809 INFO sha1sum:42 sha1 sum done for tumor.fastq.gz
2017-07-31 10:20:56,823 INFO main:916 validated all metadata objects for output
2017-07-31 10:20:56,824 INFO main:922 number of metadata files written: 2
2017-07-31 10:20:56,824 INFO main:931 Uploading files.
2017-07-31 10:20:56,824 INFO main:932 NOTE: If it hangs IP may be blocked
Traceback (most recent call last):
  File "/dcc/dcc-spinnaker-client/spinnaker.py", line 1037, in <module>
    main()
  File "/dcc/dcc-spinnaker-client/spinnaker.py", line 940, in main
    options.submissionServerUrl + "/v0/submissions", json={})
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='storage2.ucsc-cgl.org', port=8460): Max retries exceeded with url: /v0/submissions (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6669831f50>: Failed to establish a new connection: [Errno 110] Connection timed out',))
```

A quick look with netstat reveals that port 8460 is not running on the same machine I'm trying this from (the dcc-ops deployed instance itself, so no firewall rules interfering in the connection:

```
ubuntu@ip-172-31-21-238:~/spinnaker-test$ netstat -tunl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::32800                :::*                    LISTEN
tcp6       0      0 :::32802                :::*                    LISTEN
tcp6       0      0 :::32805                :::*                    LISTEN
tcp6       0      0 :::32806                :::*                    LISTEN
tcp6       0      0 :::5672                 :::*                    LISTEN
tcp6       0      0 :::32815                :::*                    LISTEN
tcp6       0      0 :::80                   :::*                    LISTEN
tcp6       0      0 :::32816                :::*                    LISTEN
tcp6       0      0 :::8080                 :::*                    LISTEN
tcp6       0      0 :::32817                :::*                    LISTEN
tcp6       0      0 :::8081                 :::*                    LISTEN
tcp6       0      0 :::32818                :::*                    LISTEN
tcp6       0      0 :::32819                :::*                    LISTEN
tcp6       0      0 :::32820                :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::15672                :::*                    LISTEN
tcp6       0      0 :::443                  :::*                    LISTEN
tcp6       0      0 :::32796                :::*                    LISTEN
tcp6       0      0 :::32797                :::*                    LISTEN
tcp6       0      0 :::32798                :::*                    LISTEN
udp        0      0 0.0.0.0:68              0.0.0.0:*
```

What am I doing wrong now? :_S

**Comment by caaespin** [comment]
I see what the error is. Try adding the `--skip-submit` flag after `spinnaker-upload`. This will stop the spinnaker client from triggering the Spinnaker validation server (which is currently not implemented yet). That's why you are seeing that `ConnectionError`.  Let me know if that helps.

**Comment by brainstorm** [comment]
Thanks @caaespin! It seems to have gone one step further but now it fails registering the metadata it seems:

```
ubuntu@ip-172-31-21-238:~/spinnaker-test$ docker run -it -e REDWOOD_ENDPOINT=storage.dcc.umccr.nopcode.org -v $(pwd)/application-redwood.properties:/dcc/dcc-redwood-client/conf/application-redwood.properties -v $(pwd):/data -v $(pwd)/three_manifest.tsv:/manifests/manifest.tsv -v $(pwd)/outputs:/outputs -v $(pwd)/samples:/samples quay.io/ucsc_cgl/core-client:1.1.1 spinnaker-upload --skip-submit /manifests/manifest.tsv
2017-08-01 09:59:11,210 INFO sha1sum:34 Calculating the sha1 sum for normal.fastq.gz.
100%|###############################################################################################################################################################################################################################################| 42.0/42.0 [00:00<00:00, 843KB/s]
2017-08-01 09:59:11,211 INFO sha1sum:42 sha1 sum done for normal.fastq.gz
2017-08-01 09:59:11,211 INFO sha1sum:34 Calculating the sha1 sum for tumor.fastq.gz.
100%|###############################################################################################################################################################################################################################################| 42.0/42.0 [00:00<00:00, 979KB/s]
2017-08-01 09:59:11,211 INFO sha1sum:42 sha1 sum done for tumor.fastq.gz
2017-08-01 09:59:11,226 INFO main:916 validated all metadata objects for output
2017-08-01 09:59:11,226 INFO main:922 number of metadata files written: 2
2017-08-01 09:59:11,227 INFO main:931 Uploading files.
2017-08-01 09:59:11,227 INFO main:932 NOTE: If it hangs IP may be blocked
2017-08-01 09:59:11,227 INFO md5sum:48 Calculating the md5 checksum for metadata.json.
100%|############################################################################################################################################################################################################################################| 1.58K/1.58K [00:00<00:00, 26.8MB/s]
2017-08-01 09:59:11,227 INFO md5sum:57 md5 checksum done for metadata.json
2017-08-01 09:59:11,228 INFO md5sum:48 Calculating the md5 checksum for normal.fastq.gz.
100%|##############################################################################################################################################################################################################################################| 42.0/42.0 [00:00<00:00, 1.05MB/s]
2017-08-01 09:59:11,228 INFO md5sum:57 md5 checksum done for normal.fastq.gz
2017-08-01 09:59:11,228 INFO main:982 counts	{"bundlesFound": 1}
2017-08-01 09:59:11,228 INFO md5sum:48 Calculating the md5 checksum for tumor.fastq.gz.
100%|###############################################################################################################################################################################################################################################| 42.0/42.0 [00:00<00:00, 667KB/s]
2017-08-01 09:59:11,229 INFO md5sum:57 md5 checksum done for tumor.fastq.gz
2017-08-01 09:59:11,229 INFO md5sum:48 Calculating the md5 checksum for metadata.json.
100%|############################################################################################################################################################################################################################################| 1.59K/1.59K [00:00<00:00, 25.6MB/s]
2017-08-01 09:59:11,230 INFO md5sum:57 md5 checksum done for metadata.json
2017-08-01 09:59:11,230 INFO main:982 counts	{"bundlesFound": 2}
2017-08-01 09:59:11,230 INFO register_upload:551 registering upload redwood metadata: dcc-metadata-client -m /outputs/registration.tsv -o /outputs/redwoodUploadManifest
2017-08-01 09:59:16,046 ERROR register_upload:558 error registering upload with redwood-metadata-server
2017-08-01 09:59:16,046 ERROR main:994 upload registration failed
```

/cc @ohofmann

**Comment by caaespin** [comment]
Try to run it with `REDWOOD_ENDPOINT` set to `dcc.umccr.nopcode.org`

**Comment by brainstorm** [comment]
Worked! Thanks!
