### ISSUE TITLE
Ansible Playbook Failure in Consonance Installation

### ISSUE THREAD

**Issue by alex-hancock** [BD2KGenomics/dcc-ops#96]
On my dcc-ops development box, I get an error when Consonance attempts to spin up an EC2 instance about privilege escalation:

`fatal: [i-079e2ecde181aac4b]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}`

Similar problem present in [this thread](https://github.com/ansible/ansible/issues/14426). [Solution given here](https://github.com/ansible/ansible/issues/14426#issuecomment-245256330) and [implemented here on line 398.](https://github.com/BD2KGenomics/dcc-ops/blob/develop/consonance/ssh.py#L398) 

However, the fix above doesn't seem to hold on my instance, and the error declares that the timeout is drastically lower than the padded timeout present in ssh.py. This is currently not affecting production, but is worth recording so we can revisit this bug if we see it in any other instance. If not, it's presumably a problem related to my installation of dcc-ops.

Full error message below:
```
21:51:19.216 [pool-1-thread-2] INFO  i.c.youxia.deployer.Deployer - [sensu-server]
sensu-server    ansible_ssh_host=127.0.0.1      ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/key.pem
[master]
i-079e2ecde181aac4b     ansible_ssh_host=54.245.209.13  ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/root/.ssh/key.pem

[all_groups:children]
master

21:51:19.216 [pool-1-thread-2] INFO  i.c.youxia.deployer.Deployer - ansible attempt #0: ansible-playbook -i /tmp/ansible8079966302753924534.inventory /container-host-bag/install.yml -e @/container-host-bag/example_params.json

PLAY [master:worker] ***********************************************************

TASK [install python2] *********************************************************
21:51:20.697 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING FOR VMs TO REAP!
21:51:20.697 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING DB FOR LOST JOB VMS TO REAP
21:51:20.698 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING DB FOR SUCCESS/FAILED JOB VMS TO REAP
21:51:20.707 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING QUEUE FOR VMS TO REAP
21:51:23.562 [pool-1-thread-1] INFO  i.c.a.c.ContainerProvisionerThreads$ProcessVMOrders - CHECKING FOR NEW VM ORDER!
21:51:25.707 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING FOR VMs TO REAP!
21:51:25.707 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING DB FOR LOST JOB VMS TO REAP
21:51:25.708 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING DB FOR SUCCESS/FAILED JOB VMS TO REAP
21:51:25.716 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING QUEUE FOR VMS TO REAP
21:51:28.563 [pool-1-thread-1] INFO  i.c.a.c.ContainerProvisionerThreads$ProcessVMOrders - CHECKING FOR NEW VM ORDER!
21:51:30.717 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING FOR VMs TO REAP!
21:51:30.717 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING DB FOR LOST JOB VMS TO REAP
21:51:30.718 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING DB FOR SUCCESS/FAILED JOB VMS TO REAP
21:51:30.728 [pool-1-thread-3] INFO  i.c.a.c.ContainerProvisionerThreads$CleanupVMs - CHECKING QUEUE FOR VMS TO REAP
fatal: [i-079e2ecde181aac4b]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
        to retry, use: --limit @/container-host-bag/install.retry

PLAY RECAP *********************************************************************
i-079e2ecde181aac4b        : ok=0    changed=0    unreachable=0    failed=1

21:51:31.756 [pool-1-thread-2] INFO  i.c.youxia.deployer.Deployer - Caught an Ansible non-zero exit code for: ansible-playbook -i /tmp/ansible8079966302753924534.inventory /container-host-bag/install.yml -e @/container-host-bag/example_params.json
21:51:31.758 [pool-1-thread-2] ERROR i.c.a.c.ContainerProvisionerThreads$ProvisionVMs - Youxia deployer threw the following exception
java.lang.RuntimeException: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
        at io.cloudbindle.youxia.deployer.Deployer.runAnsibleActual(Deployer.java:710)
        at io.cloudbindle.youxia.deployer.Deployer.prepAnsibleForAWS(Deployer.java:584)
        at io.cloudbindle.youxia.deployer.Deployer.runDeploymentForAWS(Deployer.java:749)
        at io.cloudbindle.youxia.deployer.Deployer.runDeployment(Deployer.java:732)
        at io.cloudbindle.youxia.deployer.Deployer.main(Deployer.java:1008)
        at io.consonance.arch.containerProvisioner.ContainerProvisionerThreads$ProvisionVMs.call(ContainerProvisionerThreads.java:291)
        at io.consonance.arch.containerProvisioner.ContainerProvisionerThreads$ProvisionVMs.call(ContainerProvisionerThreads.java:189)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at io.cloudbindle.youxia.deployer.Deployer.runAnsibleActual(Deployer.java:696)
        ... 10 common frames omitted21:51:31.758 [pool-1-thread-2] INFO  i.c.a.c.ContainerProvisionerThreads - Kill list contains: []
21:51:31.759 [pool-1-thread-2] INFO  i.c.a.c.ContainerProvisionerThreads - Running youxia reaper with following parameters:[--kill-list, /tmp/target5240315266006816437json]
21:51:31.763 [pool-1-thread-2] INFO  c.a.a.p.i.ProfilesConfigFileLoader - Skip unsupported property name region in profile [default].
21:51:31.847 [pool-1-thread-2] INFO  c.a.a.p.i.ProfilesConfigFileLoader - Skip unsupported property name region in profile [default].
21:51:32.101 [pool-1-thread-2] INFO  i.c.youxia.listing.AwsListing - Located 1 relevant instances on AWS
21:51:32.102 [pool-1-thread-2] INFO  c.a.a.p.i.ProfilesConfigFileLoader - Skip unsupported property name region in profile [default].
21:51:32.200 [pool-1-thread-2] INFO  i.c.youxia.reaper.AWSHelper - i-079e2ecde181aac4b is not ready, likely an orphaned VM
21:51:32.200 [pool-1-thread-2] INFO  io.cloudbindle.youxia.reaper.Reaper - i-079e2ecde181aac4b is added to kill list since it is an orphan
21:51:32.200 [pool-1-thread-2] INFO  io.cloudbindle.youxia.reaper.Reaper - Live mode:
[2017/07/13 21:51:32] | Killing {i-079e2ecde181aac4b=i-079e2ecde181aac4b},
21:51:32.203 [pool-1-thread-2] ERROR io.cloudbindle.youxia.util.Log - Could not write to slack URL
21:51:32.203 [pool-1-thread-2] INFO  c.a.a.p.i.ProfilesConfigFileLoader - Skip unsupported property name region in profile [default].
21:51:32.207 [pool-1-thread-2] WARN  i.c.youxia.reaper.AWSHelper - Marking instances for death i-079e2ecde181aac4b
21:51:32.442 [pool-1-thread-2] INFO  i.c.youxia.sensu.client.SensuClient - Looking at GET http://127.0.0.1:4567/clients HTTP/1.1
21:51:32.452 [pool-1-thread-2] ERROR i.c.a.c.ContainerProvisionerThreads - Youxia reaper threw the following exception
java.lang.RuntimeException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4567 [/127.0.0.1] failed: Connection refused (Connection refused)
        at io.cloudbindle.youxia.sensu.client.SensuClient.getXs(SensuClient.java:121)
        at io.cloudbindle.youxia.sensu.client.SensuClient.getClients(SensuClient.java:65)
        at io.cloudbindle.youxia.reaper.Reaper.terminateSensuClients(Reaper.java:347)
        at io.cloudbindle.youxia.reaper.Reaper.main(Reaper.java:505)
        at io.consonance.arch.containerProvisioner.ContainerProvisionerThreads.runReaper(ContainerProvisionerThreads.java:513)
        at io.consonance.arch.containerProvisioner.ContainerProvisionerThreads.access$000(ContainerProvisionerThreads.java:79)
        at io.consonance.arch.containerProvisioner.ContainerProvisionerThreads$ProvisionVMs.call(ContainerProvisionerThreads.java:295)
        at io.consonance.arch.containerProvisioner.ContainerProvisionerThreads$ProvisionVMs.call(ContainerProvisionerThreads.java:189)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4567 [/127.0.0.1] failed: Connection refused (Connection refused)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at io.cloudbindle.youxia.sensu.client.SensuClient.getXs(SensuClient.java:113)
        ... 11 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
        ... 20 common frames omitted
```

**Comment by alex-hancock** [comment]
Ansible fix provided maps the updated ssh.py (with a timeout value of 60s) to `/usr/lib/python2.7/dist-packages`. However, according to the python system path presented below, Ansible will use the default ssh.py located in  `/usr/local/lib/python2.7/dist-packages`. 

```
# python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print '\n'.join(sys.path)

/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
```

Need to modify the dockerfile to copy ssh.py to both filepaths, this should fix the problem.
